kind: ConfigMap
apiVersion: v1
metadata:
  name: app-config-extra
  namespace: poc-developer-hub
immutable: false
data:
  app-config-extra.yaml: |
    app:
      title: Developer Hub - Poc - v0.2
      baseUrl: https://backstage-community-poc-developer-hub.apps.k8s.dev.local
    backend:
      auth:
        externalAccess:
            - type: legacy
              options:
                subject: legacy-default-config
                secret: "pl4s3Ch4ng3M3"
      baseUrl: https://backstage-community-poc-developer-hub.apps.k8s.dev.local
      cors:
        origin: https://backstage-community-poc-developer-hub.apps.k8s.dev.local
    integrations:
      github:
        - host: github.com
          token: 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
          apps:
            - appId: 1050577
              clientId: Iv23lizJb5t1o8s6pHPB
              clientSecret: 9a1444d435c3e2f2e353928c6ec775559ee33089
              webhookUrl: https://backstage-community-poc-developer-hub.apps.k8s.dev.local
              webhookSecret: Yv3r2ZfE4dHFCjzN
              privateKey: |
                -----BEGIN RSA PRIVATE KEY-----
                MIIEpQIBAAKCAQEA6STqSe3XfuxayK3MXPYNVue/R8uZS6j12laWpOvxB+aSDVWL
                5EjBseJjweIUmXv4Ar1IUA1A+q0Xo0CxNFtyUEdubXpCGbHUIdY3VFXRYrbHCLDt
                gMqwg6bZ3QODf4T/tbRZiK88cUxlG7Qlxmr5ooXBaIGut9lMidTLm/jQc10NkRaO
                VTtLojG7MagvrSAxKdBSDSV39ExjDTJZElLfHGC8wkqPVI3+kj73ownkDX/W8fFV
                DErkKJmE7MksBiW54GCNqhKiU8jIKwD0Hy5hPgW4kRXhe6KMyd0jC2+i/sl+s2uo
                a8BG/OJHXia4D3e7jovT/0CLczc5y/vxmHMFMQIDAQABAoIBAQDfj3ll2L6qQ4Qu
                KJHtljdmXSULeE0Pwv21FxCvJlvjApKMXLqe9bFenMKhuOOd5cUFA3Ii6QKlHXOs
                JK2HkiTEnCpkqjZWIzJSG/LEWOJGMRQb3mRv+mxWYZlJmEPw9JyrJTwxmC9ySRou
                /Yi3gf7MfEvgpXHfc2w0QqvXbTidVQnOoEXSfAIjVrGtH2JnMYKX8PJj92J9YoTm
                q3BHU1RcpqWNuSKcuMt5FWp8+dL9XAqXljtlO3kVPheDrgcX0jF2ponJdmjdWyjk
                OxUFg0mcnA3EjEkQWeHA992dWkwilynOMplpSquauWLqjaLH9MT8So0AaTlQLiwU
                lX4V0rnRAoGBAPaopYNhMwbdoGEtuw1JAkmrHz11MvoPD8cwndZ+FOBS28nrBcN7
                ReGOhi+Y1CQBSeWeBbFBG8IYJpzdgUE2jnZ14OlouIAbPSaLkL+VOH2rfTG12o4r
                DKwK9DRP71SnHELaVFtmcW8GTL0HwxFfhLWyz29WxQieaEGdLh+bf0iNAoGBAPH5
                Pro15lUnmlJcmNk3yraTpPOsvn1nSrgBdA9EdAuvNjIyX3s6VJ1ToHSRvzk85ABk
                xyXvwwu4sqGo78KrehMUK4C3gNT7QeKZk5FH+GTMBJJfyr5lZNOlQGZCqTYpa1Qp
                gMslMB/rIAFHqz+FFY0jxaSr6VulL4OF1tDzvQA1AoGBAOj3cpR7GqHSc+c1NSWg
                HmwMFw6KAmLSFPnyvjFXlkolmHfG5gOzC9a1MaIE++Eh4nTgYsn/D8Or4dRpFerN
                J5NVVN+/y/sbPw+H5Gg+/UMc1Ls94rZCjM517h72nLrct0GhSumlAWB2l8Y2bZSc
                HhErWOb1ElZIn3nRhj3ONVMFAoGBAJoKexVeJNDHEmYmTqPR8bnDSjpaGTaKIDX9
                rt3dTSb3FsBj8wbmvmEdkMNE2YBdtCRQA7ux4/A9V3K0slWyhldI+tzJdTmg7nOM
                IzZUo9u/SZXJZ69HqyVVSScQftpdCdedSEGK3hUjwM8vyeP5HBwqzrKjQj62bQYE
                mRmSYRqVAoGAe/n4tR2zso4BZ7tjORo6SX21bdxQYhfikw0Xb9+DIMduCJBdLYf8
                xaC+8JCvTVk5wg4pPrEVg81lnjf7dWAE1C876mzyi6v9W8mCl6w9JI9oPv2AenNk
                ore6MMuCUNdqMj2WlURnsf15zL/Fs0mHOEifevjrieUQmGFV08wgWWU=
                -----END RSA PRIVATE KEY-----
    signInPage: github
    dangerouslyAllowSignInWithoutUserInCatalog: true

    auth:
      # see https://backstage.io/docs/auth/ to learn about auth providers
      #environment: production
      environment: development
      providers:
        github:
          development:
            clientId: Ov23liVbr04gocn6IYx5
            clientSecret: e905ebe1018132fe5088c1fa1f0d31cdc5d4c4e3
        guest:
          dangerouslyAllowOutsideDevelopment: true
          development:
            enabled: true

    #acesso ao openshift
    kubernetes:
      serviceLocatorMethod:
        type: 'multiTenant'
      clusterLocatorMethods:
        - type: "config"
          clusters:
            - name: "openshift-cluster"
              url: "https://api.apps.k8s.dev.local:6443"  # URL do servidor API do OpenShift
              serviceAccountToken:  
                $env: eyJhbGciOiJSUzI1NiIsImtpZCI6Ik01b3ZYTWZZX3VHYmNHMTVTM0lib19UMm4zY3ZoUGtWX1hCLW1IWE5nUzgifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjIl0sImV4cCI6MTczMDgyNDk1MCwiaWF0IjoxNzMwODIxMzUwLCJpc3MiOiJodHRwczovL2t1YmVybmV0ZXMuZGVmYXVsdC5zdmMiLCJrdWJlcm5ldGVzLmlvIjp7Im5hbWVzcGFjZSI6InBvYy1kZXZlbG9wZXItaHViIiwic2VydmljZWFjY291bnQiOnsibmFtZSI6ImRldmVsb3Blci1odWItc2EiLCJ1aWQiOiIzZGJlNWVhZC05NmUwLTQ3ZjYtODhkYy0yZjVjNDVmYTgyOTIifX0sIm5iZiI6MTczMDgyMTM1MCwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OnBvYy1kZXZlbG9wZXItaHViOmRldmVsb3Blci1odWItc2EifQ.QaNT6C09Hk2H1tB-GUKiGaJzjsLhIMpp3c2a6V2pDSL75bOKvas_kAff_pn9newSxh3xE5BglmuCI-tvgXk3glb-r87HWekx4L_wKTuX-OGdU9rpUlojSN7Yuo7C-whvSpYoHhKy2M89sFbUzGQNc41RCbvXZHyK_CpO18-lhAcr9tKHRWljqOW-rSAljCAg8pBJT-OqNLjMGibo5fQP71rRcarEC6e6XcbZnyOJOhEStYwWeE8aTY1Hqpc6ckggiQ3EbfJt2b58S_g05pBGGNHDTNZveLH801uyZTftfqJwRrJ_NgezUuU04E-l3ukZRGGKtWLpx9p0L_9I60OhYn12Xg21zlESdIZpSMSfocj1CMmGh0RTbY9t2NpkFsKJBUEtfzJ1cWRqFAO3lLC-PTuH_fUHpksOXS-Y4681_nqyYNpqbDyPQJbCvdTTPQb0iDdb_IGaNizZyA9ggTywbbQWBb1UrW_grChEwDCUW2lyisMXv_L-FEmyz84bodnbarTAgGFIocXCURw5P_nebuLiaeoisQZzEo3kFqRDzOV-QyGZAK6Dk56OGwFKtGVAbxd3HWK_oTxehL8hvqw8Brky19nI3sHUE6gBIuNVNZfTqER3MDSK4Ao5b0Q_lNEyPBzIb_TXsGlYQFLDYe0WTFhDyt5oSVhyava9HVljjWI
              authProvider: "serviceAccount"  # Indica que está usando uma ServiceAccount
              #serviceAccountToken: eyJhbGciOiJSUzI1NiIsImtpZCI6Ik01b3ZYTWZZX3VHYmNHMTVTM0lib19UMm4zY3ZoUGtWX1hCLW1IWE5nUzgifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjIl0sImV4cCI6MTczMDgyNDk1MCwiaWF0IjoxNzMwODIxMzUwLCJpc3MiOiJodHRwczovL2t1YmVybmV0ZXMuZGVmYXVsdC5zdmMiLCJrdWJlcm5ldGVzLmlvIjp7Im5hbWVzcGFjZSI6InBvYy1kZXZlbG9wZXItaHViIiwic2VydmljZWFjY291bnQiOnsibmFtZSI6ImRldmVsb3Blci1odWItc2EiLCJ1aWQiOiIzZGJlNWVhZC05NmUwLTQ3ZjYtODhkYy0yZjVjNDVmYTgyOTIifX0sIm5iZiI6MTczMDgyMTM1MCwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OnBvYy1kZXZlbG9wZXItaHViOmRldmVsb3Blci1odWItc2EifQ.QaNT6C09Hk2H1tB-GUKiGaJzjsLhIMpp3c2a6V2pDSL75bOKvas_kAff_pn9newSxh3xE5BglmuCI-tvgXk3glb-r87HWekx4L_wKTuX-OGdU9rpUlojSN7Yuo7C-whvSpYoHhKy2M89sFbUzGQNc41RCbvXZHyK_CpO18-lhAcr9tKHRWljqOW-rSAljCAg8pBJT-OqNLjMGibo5fQP71rRcarEC6e6XcbZnyOJOhEStYwWeE8aTY1Hqpc6ckggiQ3EbfJt2b58S_g05pBGGNHDTNZveLH801uyZTftfqJwRrJ_NgezUuU04E-l3ukZRGGKtWLpx9p0L_9I60OhYn12Xg21zlESdIZpSMSfocj1CMmGh0RTbY9t2NpkFsKJBUEtfzJ1cWRqFAO3lLC-PTuH_fUHpksOXS-Y4681_nqyYNpqbDyPQJbCvdTTPQb0iDdb_IGaNizZyA9ggTywbbQWBb1UrW_grChEwDCUW2lyisMXv_L-FEmyz84bodnbarTAgGFIocXCURw5P_nebuLiaeoisQZzEo3kFqRDzOV-QyGZAK6Dk56OGwFKtGVAbxd3HWK_oTxehL8hvqw8Brky19nI3sHUE6gBIuNVNZfTqER3MDSK4Ao5b0Q_lNEyPBzIb_TXsGlYQFLDYe0WTFhDyt5oSVhyava9HVljjWI
              # Usar em desenvolvimento; desativar em produção
              skipTLSVerify: true
    
    catalog:
      providers:
        threeScaleApiEntity:
          dev:
            baseUrl: https://3scale-admin.apps.k8s.dev.local
            accessToken: c72591af87d56780aeffae150c8eac10c0a623a7b87956aa85e1680df6e6cd3f
            schedule: # optional; same options as in TaskScheduleDefinition
              # supports cron, ISO duration, "human duration" as used in code
              frequency: { minutes: 30 }
              # supports ISO duration, "human duration" as used in code
              timeout: { minutes: 3 }
              
    permission:
      enabled: true
      rbac:
        admin:
          users:
            - name: user:default/<your_policy_administrator_name>   # administrador