kind: ConfigMap
apiVersion: v1
metadata:
  name: app-config-extra
  namespace: poc-backstage
immutable: false
data:
  app-config-extra.yaml: |
    app:
      title: Dev Hub - Communitario - v0.1
      baseUrl: https://rhdh-community-backstage-poc-backstage.apps.k8s.dev.local
    backend:
      auth:
        externalAccess:
            - type: legacy
              options:
                subject: legacy-default-config
                secret: "pl4s3Ch4ng3M3"
      baseUrl: https://rhdh-community-backstage-poc-backstage.apps.k8s.dev.local
      cors:
        origin: https://rhdh-community-backstage-poc-backstage.apps.k8s.dev.local
    integrations:
      github:
        - host: github.com
          token: ${GITHUB_TOKEN}
          apps:
            - appId: 1070153
              clientId: ${GITHUB_CLIENT_ID}
              clientSecret: ${GITHUB_CLIENT_SECRET}
              webhookUrl: https://rhdh-community-backstage-poc-backstage.apps.k8s.dev.local
              webhookSecret: Yv3r2ZfE4dHFCjzN
              privateKey: |
                -----BEGIN RSA PRIVATE KEY-----
                MIIEpAIBAAKCAQEApmcpY7U3tiyDczNPIP7My68QboCGtxyPGs+sMYR0A1Nog++F
                5ECaQJt4A05J5AhUFwvHKoS0RtI2MiPOS25WFWj1zuTjnFQN024/O4eNYJfan7lm
                GFr4qQigSoEnb5BOQiF9dMB1kHMQtW9POBk57YUL96sBp+GTroixFRWgA0eY+9s1
                EfSvxL5RdGKs+JYXY5QoMJzsXI+Ekc4vHtLALIGfEJhUPAjCryC7Hhmwwpipihg6
                EYOTTq/6Hf0YoJ+1UCIKpdk5Ehsq+5+RAs2U/EP1Bpo1vuF4MN516f5EwsyHlMSX
                KJAUa9Db7r5pitNC0y0SW5B9TmPoY3ghg/W+JQIDAQABAoIBAANDQI+A7R+4TbeD
                iQinllJkE1lnUbzjZXbsHX83DqNGDmWP27s2/Q9JPRgrf81l0GhHRddylKpS0tc2
                1oOqHSv8S92LpV7aUw8TOVAsfzwmnhXFp9fQaNG/pozvbVuFo9MuHuycHXIAn5I/
                JXl/HSCoHCz2AGlPRfsFGRvFucZ2p9NQ205azv2BimLTPGnTxoejuyRbNdSIc6Kh
                lpXc5zY1vc0Z8SCU0tIoxuLww2nQEJCABDOYvPdYK8S84ilhcChnhK1ZN2Jnvz5U
                T286WSMuODqaIZzqT8fYkALy4RKOygy1SW+r0isA8LX0YY9Uan6WUJBCqqbxuhjI
                XwEj210CgYEA1KCt8q7nTD7P9v8574s+ibI+9N9h7kFZtR30btorP8QdgxFp2Nqb
                HjWPwYplauUBT8Uz2oDss1B4ZZb6HpAsxcr6zx8tbaLheQMqrFVgwEfp9In/CeO7
                ++ok6imERm+MbDVNKlQxPYN9WUOcBl4XR8hentB/DlU71nLsqfSWywcCgYEAyFim
                diR5TFnMG9RDY13D2+d4G5evTQycYEUwK48Q4AL/Ggkxn7vigWpObPuRia95ymqH
                ZWtYzgvvo3y4r+axL01viKbEWicUtb2Ta9eBFCaiPOLvMzfMsW/lNDEPAdL6qB+m
                A6YZitb46+Dn6bUBvkdoa3W0nRIu1d9RiTBepnMCgYAwjw2KyeTq5cFq4Djj+wHq
                QnncRJPB7MzG7zNeiZas9mXjA/wPWUVprcPJ6Ihm1CvrgtbnxN/Jx8vnL4apqjV/
                am7DFJS0YClsEIwTVWBGKWZFwaosIQVSb9PEYnzh9SG1qKqZyyZ/rOLYmvcsARsB
                +sGZNXZ+2HpU7GQeIEy7ywKBgQDB/NyJbn2oyRYSKDBr6WF47yJkDTZnM3vC15tx
                weBEF4Ks0hQjp4gFaUqwydG88JTLwuSA9jURpYsO0Pf/Ei+kLqV9OoTLCiZKZ1p0
                REGuok3bCJ02CaSAdmkHZS0zxfaAjcxwogb/YXG665WCvIoIlRntWxZcNDv3SHmp
                jZVIMwKBgQCS3PJ1QEj8wgE46eZg95zPlFdrRaPAm02tIV2CzG4bQ37btE+4B6D9
                f8id58hPQiM0xj8nbB2BD/yIgJlEybpHBU5J6air5oZZq+Lni+CseIs4cuI0m5Tw
                mlEg7OKgQQAjTlkAjk4A1oUr1kY4oFMjQ6IN0wnWaizWEFXG0mNgbw==
                -----END RSA PRIVATE KEY-----
    signInPage: github
    dangerouslyAllowSignInWithoutUserInCatalog: true

    auth:
      # see https://backstage.io/docs/auth/ to learn about auth providers
      #environment: production
      environment: development
      providers:
        github:
          development:
            clientId: ${GITHUB_CLIENT_ID}
            clientSecret: ${GITHUB_CLIENT_SECRET}
        guest:
          dangerouslyAllowOutsideDevelopment: true
          development:
            enabled: true

    #acesso ao openshift
    kubernetes:
      serviceLocatorMethod:
        type: 'multiTenant'
      clusterLocatorMethods:
        - type: "config"
          clusters:
            - name: "openshift-cluster"
              url: "https://api.apps.k8s.dev.local:6443"  # URL do servidor API do OpenShift
              serviceAccountToken:  
                $env: eyJhbGciOiJSUzI1NiIsImtpZCI6Ik01b3ZYTWZZX3VHYmNHMTVTM0lib19UMm4zY3ZoUGtWX1hCLW1IWE5nUzgifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjIl0sImV4cCI6MTczMDgyNDk1MCwiaWF0IjoxNzMwODIxMzUwLCJpc3MiOiJodHRwczovL2t1YmVybmV0ZXMuZGVmYXVsdC5zdmMiLCJrdWJlcm5ldGVzLmlvIjp7Im5hbWVzcGFjZSI6InBvYy1kZXZlbG9wZXItaHViIiwic2VydmljZWFjY291bnQiOnsibmFtZSI6ImRldmVsb3Blci1odWItc2EiLCJ1aWQiOiIzZGJlNWVhZC05NmUwLTQ3ZjYtODhkYy0yZjVjNDVmYTgyOTIifX0sIm5iZiI6MTczMDgyMTM1MCwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OnBvYy1kZXZlbG9wZXItaHViOmRldmVsb3Blci1odWItc2EifQ.QaNT6C09Hk2H1tB-GUKiGaJzjsLhIMpp3c2a6V2pDSL75bOKvas_kAff_pn9newSxh3xE5BglmuCI-tvgXk3glb-r87HWekx4L_wKTuX-OGdU9rpUlojSN7Yuo7C-whvSpYoHhKy2M89sFbUzGQNc41RCbvXZHyK_CpO18-lhAcr9tKHRWljqOW-rSAljCAg8pBJT-OqNLjMGibo5fQP71rRcarEC6e6XcbZnyOJOhEStYwWeE8aTY1Hqpc6ckggiQ3EbfJt2b58S_g05pBGGNHDTNZveLH801uyZTftfqJwRrJ_NgezUuU04E-l3ukZRGGKtWLpx9p0L_9I60OhYn12Xg21zlESdIZpSMSfocj1CMmGh0RTbY9t2NpkFsKJBUEtfzJ1cWRqFAO3lLC-PTuH_fUHpksOXS-Y4681_nqyYNpqbDyPQJbCvdTTPQb0iDdb_IGaNizZyA9ggTywbbQWBb1UrW_grChEwDCUW2lyisMXv_L-FEmyz84bodnbarTAgGFIocXCURw5P_nebuLiaeoisQZzEo3kFqRDzOV-QyGZAK6Dk56OGwFKtGVAbxd3HWK_oTxehL8hvqw8Brky19nI3sHUE6gBIuNVNZfTqER3MDSK4Ao5b0Q_lNEyPBzIb_TXsGlYQFLDYe0WTFhDyt5oSVhyava9HVljjWI
              authProvider: "serviceAccount"  # Indica que está usando uma ServiceAccount
              #serviceAccountToken: eyJhbGciOiJSUzI1NiIsImtpZCI6Ik01b3ZYTWZZX3VHYmNHMTVTM0lib19UMm4zY3ZoUGtWX1hCLW1IWE5nUzgifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjIl0sImV4cCI6MTczMDgyNDk1MCwiaWF0IjoxNzMwODIxMzUwLCJpc3MiOiJodHRwczovL2t1YmVybmV0ZXMuZGVmYXVsdC5zdmMiLCJrdWJlcm5ldGVzLmlvIjp7Im5hbWVzcGFjZSI6InBvYy1kZXZlbG9wZXItaHViIiwic2VydmljZWFjY291bnQiOnsibmFtZSI6ImRldmVsb3Blci1odWItc2EiLCJ1aWQiOiIzZGJlNWVhZC05NmUwLTQ3ZjYtODhkYy0yZjVjNDVmYTgyOTIifX0sIm5iZiI6MTczMDgyMTM1MCwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OnBvYy1kZXZlbG9wZXItaHViOmRldmVsb3Blci1odWItc2EifQ.QaNT6C09Hk2H1tB-GUKiGaJzjsLhIMpp3c2a6V2pDSL75bOKvas_kAff_pn9newSxh3xE5BglmuCI-tvgXk3glb-r87HWekx4L_wKTuX-OGdU9rpUlojSN7Yuo7C-whvSpYoHhKy2M89sFbUzGQNc41RCbvXZHyK_CpO18-lhAcr9tKHRWljqOW-rSAljCAg8pBJT-OqNLjMGibo5fQP71rRcarEC6e6XcbZnyOJOhEStYwWeE8aTY1Hqpc6ckggiQ3EbfJt2b58S_g05pBGGNHDTNZveLH801uyZTftfqJwRrJ_NgezUuU04E-l3ukZRGGKtWLpx9p0L_9I60OhYn12Xg21zlESdIZpSMSfocj1CMmGh0RTbY9t2NpkFsKJBUEtfzJ1cWRqFAO3lLC-PTuH_fUHpksOXS-Y4681_nqyYNpqbDyPQJbCvdTTPQb0iDdb_IGaNizZyA9ggTywbbQWBb1UrW_grChEwDCUW2lyisMXv_L-FEmyz84bodnbarTAgGFIocXCURw5P_nebuLiaeoisQZzEo3kFqRDzOV-QyGZAK6Dk56OGwFKtGVAbxd3HWK_oTxehL8hvqw8Brky19nI3sHUE6gBIuNVNZfTqER3MDSK4Ao5b0Q_lNEyPBzIb_TXsGlYQFLDYe0WTFhDyt5oSVhyava9HVljjWI
              # Usar em desenvolvimento; desativar em produção
              skipTLSVerify: true
    
    catalog:
      providers:
        threeScaleApiEntity:
          dev:
            baseUrl: https://3scale-admin.apps.k8s.dev.local
            accessToken: c72591af87d56780aeffae150c8eac10c0a623a7b87956aa85e1680df6e6cd3f
            schedule: # optional; same options as in TaskScheduleDefinition
              # supports cron, ISO duration, "human duration" as used in code
              frequency: { minutes: 30 }
              # supports ISO duration, "human duration" as used in code
              timeout: { minutes: 3 }
              
    permission:
      enabled: true
      rbac:
        admin:
          users:
            - name: user:default/<your_policy_administrator_name>   # administrador