kind: ConfigMap
apiVersion: v1
metadata:
  name: app-config-extra
  namespace: poc-backstage
immutable: false
data:
  app-config-extra.yaml: |
    app:
      title: Dev Hub - Community - v0.1
      baseUrl: https://rhdh-community-backstage-poc-backstage.apps.k8s.dev.local
    backend:
      auth:
        externalAccess:
            - type: legacy
              options:
                subject: legacy-default-config
                secret: "pl4s3Ch4ng3M3"
      baseUrl: https://rhdh-community-backstage-poc-backstage.apps.k8s.dev.local
      cors:
        origin: https://rhdh-community-backstage-poc-backstage.apps.k8s.dev.local
    integrations:
      github:
        - host: github.com
          token: ${GITHUB_TOKEN}
          apps:
            - appId: 1070153
              clientId: ${GITHUB_CLIENT_ID}
              clientSecret: ${GITHUB_CLIENT_SECRET}
              webhookUrl: https://rhdh-community-backstage-poc-backstage.apps.k8s.dev.local
              webhookSecret: ${GITHUB_WEBHOOKSECRET}
              privateKey: ${GITHUB_PRIVATE_KEY}
    signInPage: github
    dangerouslyAllowSignInWithoutUserInCatalog: true

    auth:
      # see https://backstage.io/docs/auth/ to learn about auth providers
      #environment: production
      environment: development
      providers:
        github:
          development:
            clientId: ${GITHUB_CLIENT_ID}
            clientSecret: ${GITHUB_CLIENT_SECRET}
        guest:
          dangerouslyAllowOutsideDevelopment: true
          development:
            enabled: true

    #acesso ao openshift
    kubernetes:
      serviceLocatorMethod:
        type: 'multiTenant'
      clusterLocatorMethods:
        - type: "config"
          clusters:
            - name: ${OPENSHIFT_CLUSTER_NAME}
              url: ${OPENSHIFT_CLUSTER_URL}  # URL do servidor API do OpenShift
              authProvider: "serviceAccount"  # Indica que está usando uma ServiceAccount
              #serviceAccountToken: eyJhbGciOiJSUzI1NiIsImtpZCI6Ik01b3ZYTWZZX3VHYmNHMTVTM0lib19UMm4zY3ZoUGtWX1hCLW1IWE5nUzgifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjIl0sImV4cCI6MTczMDgyNDk1MCwiaWF0IjoxNzMwODIxMzUwLCJpc3MiOiJodHRwczovL2t1YmVybmV0ZXMuZGVmYXVsdC5zdmMiLCJrdWJlcm5ldGVzLmlvIjp7Im5hbWVzcGFjZSI6InBvYy1kZXZlbG9wZXItaHViIiwic2VydmljZWFjY291bnQiOnsibmFtZSI6ImRldmVsb3Blci1odWItc2EiLCJ1aWQiOiIzZGJlNWVhZC05NmUwLTQ3ZjYtODhkYy0yZjVjNDVmYTgyOTIifX0sIm5iZiI6MTczMDgyMTM1MCwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OnBvYy1kZXZlbG9wZXItaHViOmRldmVsb3Blci1odWItc2EifQ.QaNT6C09Hk2H1tB-GUKiGaJzjsLhIMpp3c2a6V2pDSL75bOKvas_kAff_pn9newSxh3xE5BglmuCI-tvgXk3glb-r87HWekx4L_wKTuX-OGdU9rpUlojSN7Yuo7C-whvSpYoHhKy2M89sFbUzGQNc41RCbvXZHyK_CpO18-lhAcr9tKHRWljqOW-rSAljCAg8pBJT-OqNLjMGibo5fQP71rRcarEC6e6XcbZnyOJOhEStYwWeE8aTY1Hqpc6ckggiQ3EbfJt2b58S_g05pBGGNHDTNZveLH801uyZTftfqJwRrJ_NgezUuU04E-l3ukZRGGKtWLpx9p0L_9I60OhYn12Xg21zlESdIZpSMSfocj1CMmGh0RTbY9t2NpkFsKJBUEtfzJ1cWRqFAO3lLC-PTuH_fUHpksOXS-Y4681_nqyYNpqbDyPQJbCvdTTPQb0iDdb_IGaNizZyA9ggTywbbQWBb1UrW_grChEwDCUW2lyisMXv_L-FEmyz84bodnbarTAgGFIocXCURw5P_nebuLiaeoisQZzEo3kFqRDzOV-QyGZAK6Dk56OGwFKtGVAbxd3HWK_oTxehL8hvqw8Brky19nI3sHUE6gBIuNVNZfTqER3MDSK4Ao5b0Q_lNEyPBzIb_TXsGlYQFLDYe0WTFhDyt5oSVhyava9HVljjWI
              # Usar em desenvolvimento; desativar em produção
              skipTLSVerify: true
    
    argocd:
      appLocatorMethods:
        - type: 'config'
          instances:
            - name: ktoolsArgoInstance
              url: https://argocd-server-poc-ktools.apps.k8s.dev.local
              username: ${ARGOCD_USERNAME}
              password: ${ARGOCD_PASSWORD}